### ISSUE TITLE
Could not render layout: undefined method `compact' for nil:NilClass

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#41]
This error can re-produced from same application in different VM Centos Servers.
But once we click to call same menu. Sometime no error, I don't know if it was the cache issue or code in application but all over with oters menu of the app as well.
===================================================================

Could not render layout: undefined method `compact' for nil:NilClass
Extracted source (around line #412):
    
        value = _layout(formats) if action_has_layout?
      rescue NameError => e
        raise e, "Could not render layout: #{e.message}"
      end

      if require_layout && action_has_layout? && !value

**Comment by kul1** [comment]
Application Trace | Framework Trace | Full Trace
actionview (5.0.7.2) lib/action_view/layouts.rb:412:in `rescue in _default_layout'
actionview (5.0.7.2) lib/action_view/layouts.rb:409:in `_default_layout'
actionview (5.0.7.2) lib/action_view/layouts.rb:386:in `block in _layout_for_option'
/home/QA-USA/pkul/.rvm/gems/ruby-2.2.3/bundler/gems/app_perf_rpm-4c85edeb28c3/lib/app_perf_rpm/instruments/action_view.rb:193:in `call'
/home/QA-USA/pkul/.rvm/gems/ruby-2.2.3/bundler/gems/app_perf_rpm-4c85edeb28c3/lib/app_perf_rpm/instruments/action_view.rb:193:in `render_template'
actionview (5.0.7.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.7.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.7.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.7.2) lib/action_view/rendering.rb:104:in `_render_template'
actionpack (5.0.7.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.7.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.7.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.7.2) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.7.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/QA-USA/pkul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (5.0.7.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.7.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.7.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.7.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.7.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/QA-USA/pkul/.rvm/gems/ruby-2.2.3/bundler/gems/app_perf_rpm-4c85edeb28c3/lib/app_perf_rpm/instruments/action_controller.rb:16:in `process_action_with_trace'
actionpack (5.0.7.2) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.7.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.7.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.7.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
rack-attack (5.4.2) lib/rack/attack.rb:182:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:22:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
/home/QA-USA/pkul/.rvm/gems/ruby-2.2.3/bundler/gems/app_perf_rpm-4c85edeb28c3/lib/app_perf_rpm/instruments/rack.rb:76:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `call'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
