### ISSUE TITLE
vmstat-2.3.1/lib/vmstat/procfs.rb:150:in `initialize': No such file or directory @ rb_sysopen - /proc/vmstat (Errno::ENOENT)

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#43]
Ubuntu WSL Windows 10
Ruby 2.6.3
Tried start both bundle exec foreman start after bin/setup 
and run seperate rails s and app_perf_agent
```
I, [2019-06-26T12:46:40.951870 #1004]  INFO -- : Initializing with options: {:license_key=>"30b5805c-25d8-4fcd-875e-4fd9be32993e", :host=>"localhost:5000"}
I, [2019-06-26T12:46:40.966285 #1004]  INFO -- : Loading CPU monitoring.
I, [2019-06-26T12:46:40.967592 #1004]  INFO -- : Loading Disk monitoring.
I, [2019-06-26T12:46:40.968686 #1004]  INFO -- : Loading Load monitoring.
I, [2019-06-26T12:46:40.969730 #1004]  INFO -- : Loading Memory monitoring.
I, [2019-06-26T12:46:40.970760 #1004]  INFO -- : Loading Network monitoring.
I, [2019-06-26T12:46:40.970805 #1004]  INFO -- : Starting AppPerfAgent.
Traceback (most recent call last):
        18: from /home/prateep/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        17: from /home/prateep/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        16: from /home/prateep/.rvm/gems/ruby-2.6.3/bin/app_perf_agent:23:in `<main>'
        15: from /home/prateep/.rvm/gems/ruby-2.6.3/bin/app_perf_agent:23:in `load'
        14: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/exe/app_perf_agent:7:in `<top (required)>'
        13: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/cli.rb:27:in `run'
        12: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/worker.rb:23:in `start'
        11: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/worker.rb:35:in `collect'
        10: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `plugins'
         9: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `map'
         8: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `new'
         7: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin/system/cpu.rb:11:in `initialize'
         6: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat.rb:83:in `snapshot'
         5: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat.rb:83:in `new'
         4: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat/snapshot.rb:28:in `initialize'
         3: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat/procfs.rb:69:in `memory'
         2: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat/procfs.rb:150:in `procfs_file'
         1: from /home/prateep/.rvm/gems/ruby-2.6.3/gems/vmstat-2.3.1/lib/vmstat/procfs.rb:150:in `open'
```

**Comment by randy-girard** [comment]
I have a feeling this is a windows issue as I don't believe that GEM is windows compatible. You can comment the agent out from the Procfile and it should be able to start up.

**Comment by kul1** [comment]
I believed so. 
Here list of what I already test and work
Windows 10, and in WSL Ubuntu 
Window 10 Enterprise
which same gem, ruby version able to run in VM Centos
I will tried to remove vmstat and see if it work on other features (except cpu) in Windows
Thanks

**Comment by randy-girard** [comment]
currently the agent gets all of the system/host metrics using vmstat, so it likely wont be able to report anything under Hosts.
